# -*- coding: utf-8 -*-
"""Apps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWOscAgCasq0aciMhw4AT9DqNf7Pf-x6
"""

import streamlit as st
import random
from PIL import Image

st.set_page_config(page_title="Aya Celestia 💖", page_icon="🌸", layout="centered")

st.markdown("<h1 style='text-align: center; color: pink;'>Hai Aya Celestia! 🌸</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; font-size: 18px;'>Cuma ingin bikin kamu senyum sebentar hari ini.💖</p>", unsafe_allow_html=True)

name = st.text_input("Tulis nama kamu di sini 😚")
if name:
    st.success(f"Halo {name}! Kamu cantik banget hari ini 😍")

if st.button("Klik untuk dapat pujian 💌"):
    compliments = [
        "Kamu seperti matahari pagi, selalu membawa semangat 🌞",
        "Tawa kamu menular banget, bikin hati hangat 💕",
        "Setiap hari jadi lebih indah kalau ada kamu 🫶",
        "Kamu itu kayak lagu favorit, nggak pernah bosen didengerin 🎵",
        "Lucunya kamu tuh nggak ada obat 🐰"
    ]
    st.info(random.choice(compliments))

# 📸 Gallery lucu
st.markdown("## 😹 Mood Booster Hari Ini")
st.image("cat_smile.jpeg", caption="Mood hari ini?", use_column_width=True)

# 📝 Kotak Pesan ke Felix
msg = st.text_input("Mau nitip pesan ke Felix?")
if msg:
    st.success("Hehe noted~ Felix pasti baca 😎🫶")

# 📜 Surat dari Felix
with st.expander("📜 Buka surat dari Felix"):
    st.write(\"\"\"
    Dear Aya,

    Kamu itu seperti senja yang selalu dinanti.
    Kehadiranmu bikin semuanya terasa hangat dan nyaman.
    Aku cuma pengin bilang satu hal:
    Aku seneng banget kenal kamu 🥹

    🌸 Salam hangat,
    Felix
    \"\"\")

# 💡 Fun Fact Tentang Felix
st.markdown("## 🐣 Fun Fact Tentang Felix")
facts = [
    "Suka banget nasi goreng jam 11 malam 🍛",
    "Nggak bisa minum kopi tapi sok ngopi ☕",
    "Pernah nulis puisi, terus malu sendiri 🙈"
]
if st.button("Fun Fact Hari Ini"):
    st.info(random.choice(facts))

# 🎉 Hadiah & Balon
if st.button("Buka hadiah dari Felix 🎁"):
    st.balloons()
    st.success("Kamu dapet peluk virtual terhangat hari ini 🤗💗")